"""document tables, columns

Revision ID: 052eae0af0e0
Revises: 1c820fbb92d5
Create Date: 2026-01-13 17:39:07.600130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "052eae0af0e0"
down_revision: Union[str, Sequence[str], None] = "1c820fbb92d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "origins",
        "country",
        existing_type=sa.VARCHAR(),
        comment="Two letter country code (ISO 3166-1 alpha-2)",
        existing_nullable=False,
    )
    op.alter_column(
        "roasters",
        "country",
        existing_type=sa.VARCHAR(),
        nullable=False,
        comment="Two letter country code (ISO 3166-1 alpha-2)",
    )
    op.alter_column(
        "roasters",
        "equipment_capacity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Size of the roasting machine in kg.",
        existing_nullable=True,
    )
    op.create_table_comment(
        "roasters",
        "Identity information of companies, people, or users that roast coffees.",
        existing_comment=None,
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "roasters",
        existing_comment="Identity information of companies, people, or users that roast coffees.",
        schema=None,
    )
    op.alter_column(
        "roasters",
        "equipment_capacity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Size of the roasting machine in kg.",
        existing_nullable=True,
    )
    op.alter_column(
        "roasters",
        "country",
        existing_type=sa.VARCHAR(),
        nullable=True,
        comment=None,
        existing_comment="Two letter country code (ISO 3166-1 alpha-2)",
    )
    op.alter_column(
        "origins",
        "country",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Two letter country code (ISO 3166-1 alpha-2)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
