"""refactor array types, defaults, updates

Revision ID: 1c820fbb92d5
Revises: 0bfe0c4beb52
Create Date: 2026-01-13 14:46:35.537801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c820fbb92d5"
down_revision: Union[str, Sequence[str], None] = "0bfe0c4beb52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "green_coffees",
        "varieties",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default="[]",
        type_=postgresql.JSON(astext_type=sa.Text()),
        postgresql_using="array_to_json(varieties)",
        nullable=False,
    )
    op.alter_column(
        "green_coffees",
        "details",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default="{}",
        nullable=False,
    )
    op.alter_column(
        "roasted_coffee_components",
        "date_added",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "roasted_coffee_components",
        "date_updated",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "roasted_coffees",
        "profile",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default="[]",
        type_=postgresql.JSON(astext_type=sa.Text()),
        postgresql_using="array_to_json(profile)",
        nullable=False,
        existing_comment="A list of the roaster's intended roast attributes, e.g. dark roast, espresso, cold brew.",
    )
    op.alter_column(
        "roasted_coffees",
        "notes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default="[]",
        type_=postgresql.JSON(astext_type=sa.Text()),
        postgresql_using="array_to_json(notes)",
        nullable=False,
        existing_comment="A list of the roaster's tasting notes.",
    )
    op.alter_column(
        "roasted_coffees",
        "prices",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default="[]",
        nullable=False,
    )
    op.alter_column(
        "roasted_coffees",
        "date_added",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "roasted_coffees",
        "date_updated",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "roasters",
        "details",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default="{}",
        existing_comment="Can include contact information, website, socials profiles, location details, etc.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###

    op.alter_column(
        "roasters",
        "country",
        existing_type=sa.VARCHAR(),
        type_=sa.VARCHAR(2),
    )

    op.alter_column(
        "origins",
        "country",
        existing_type=sa.VARCHAR(),
        type_=sa.VARCHAR(2),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roasters",
        "details",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        existing_comment="Can include contact information, website, socials profiles, location details, etc.",
        existing_nullable=True,
    )
    op.alter_column(
        "roasted_coffees",
        "date_updated",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "roasted_coffees",
        "date_added",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "roasted_coffees",
        "prices",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "roasted_coffees",
        "notes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        nullable=True,
        existing_comment="A list of the roaster's tasting notes.",
    )
    op.alter_column(
        "roasted_coffees",
        "notes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        postgresql_using="translate(json_serialize(notes), '[]', '{}')::text[]",
        existing_nullable=True,
        existing_comment="A list of the roaster's tasting notes.",
    )
    op.alter_column(
        "roasted_coffees",
        "profile",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        nullable=True,
        existing_comment="A list of the roaster's intended roast attributes, e.g. dark roast, espresso, cold brew.",
    )
    op.alter_column(
        "roasted_coffees",
        "profile",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        postgresql_using="translate(json_serialize(profile), '[]', '{}')::text[]",
        existing_nullable=True,
        existing_comment="A list of the roaster's intended roast attributes, e.g. dark roast, espresso, cold brew.",
    )
    op.alter_column(
        "roasted_coffee_components",
        "date_updated",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "roasted_coffee_components",
        "date_added",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "green_coffees",
        "details",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "green_coffees",
        "varieties",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "green_coffees",
        "varieties",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        type_=postgresql.ARRAY(sa.VARCHAR()),
        postgresql_using="translate(json_serialize(varieties), '[]', '{}')::text[]",
        nullable=True,
    )
    # ### end Alembic commands ###

    op.alter_column(
        "roasters",
        "country",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.VARCHAR(),
    )

    op.alter_column(
        "origins",
        "country",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.VARCHAR(),
    )
