"""create association: roasted, green coffees

Revision ID: 10952d968062
Revises: 762c128d99d2
Create Date: 2026-01-02 08:24:50.055195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10952d968062'
down_revision: Union[str, Sequence[str], None] = '762c128d99d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roasted_coffee_components',
    sa.Column('roasted_id', sa.Integer(), nullable=False),
    sa.Column('green_id', sa.Integer(), nullable=False),
    sa.Column('fraction', sa.Integer(), nullable=True, comment='Percentage of blend constituted by green coffee.'),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('date_removed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['green_id'], ['green_coffees.id'], ),
    sa.ForeignKeyConstraint(['roasted_id'], ['roasted_coffees.id'], ),
    sa.PrimaryKeyConstraint('roasted_id', 'green_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roasted_coffee_components')
    # ### end Alembic commands ###
