"""fix green coffees: allow null name for generics

Revision ID: 0bfe0c4beb52
Revises: 10952d968062
Create Date: 2026-01-06 07:58:54.623081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = "0bfe0c4beb52"
down_revision: Union[str, Sequence[str], None] = "10952d968062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

green_coffees = table(
    "green_coffees",
    column("name", sa.String),
    column("region_id", sa.Integer),
    column("process", sa.String),
)
origins = table(
    "origins",
    column("id", sa.Integer),
    column("country", sa.String),
    column("region", sa.String),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "green_coffees",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=True,
        comment="Green coffees without an assigned name refer to generic/unknown coffee of the specified region.",
    )
    # ### end Alembic commands ###

    # Reset region-generic coffee names to null
    op.execute(
        green_coffees.update()
        .where(green_coffees.c.name.like("_GENERIC%"))
        .values({"name": None})
    )


def downgrade() -> None:
    """Downgrade schema."""

    # Give a default name to region-generic green coffees before adding nonnull
    # constraint
    origin_subq = (
        sa.select(
            sa.func.concat(
                "_GENERIC ",
                origins.c.country,
                sa.case((origins.c.region == None, ""), else_="_"),
                sa.func.coalesce(origins.c.region),
                sa.case((green_coffees.c.process == None, ""), else_=" "),
                sa.func.coalesce(green_coffees.c.process),
            )
        )
        .where(origins.c.id == green_coffees.c.region_id)
        .scalar_subquery()
    )

    op.execute(
        green_coffees.update()
        .where(green_coffees.c.name == None)
        .values({"name": origin_subq})
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "green_coffees",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=False,
        comment=None,
        existing_comment="Green coffees without an assigned name refer to generic/unknown coffee of the specified region.",
    )
    # ### end Alembic commands ###
